Responsive
wolox-training/lfr-react pull request #10
Opened 2018-09-27 20:50 UTC by unidrelyn

## Summary

Design is made to be responsive to sizes smaller than 1024px

## Screenshot 

![image](https://user-images.githubusercontent.com/25165141/46173796-e93ac700-c26c-11e8-9025-84b91060fdb2.png)

#Trello card

https://trello.com/c/slVfYO9q/15-dise%C3%B1o-responsive

2018-09-27 22:50 UTC, FrankIglesias requested changes

2018-09-27 22:50 UTC, FrankIglesias commented on Maquetacion/scss/tech.scss
> +    grid-auto-columns: 1fr;
define the main class here you are applying these props

2018-09-27 22:50 UTC, FrankIglesias commented on Maquetacion/scss/titles.scss
> +  @media (min-width: 1024px) {
same here

2018-10-01 16:57 UTC, FrankIglesias requested changes

2018-10-01 16:57 UTC, FrankIglesias commented on Maquetacion/scss/footer.scss
> +  .footer-bar {
.footer-bar .copy {

2018-10-01 16:57 UTC, FrankIglesias commented on Maquetacion/scss/navbar.scss
> +  .nav-bar {
same

2018-10-01 17:06 UTC, jmtov submitted a review, later dismissed
Good job! 👍

2018-10-01 17:19 UTC, FrankIglesias approved these changes

2018-10-01 17:20 UTC, merged